version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://bitfamily:bitfamily@db:5432/bitfamily
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health/simple"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bitfamily
      - POSTGRES_USER=bitfamily
      - POSTGRES_PASSWORD=bitfamily
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitfamily"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
